### PR TITLE
update Atweaks to version 4.51

### PR DESCRIPTION
**Pull request by vancv**
Polish language is already in upstream.

### CODE REVIEW

**Comment by lynxlynxlynx** [comment]
Thanks! Was the remaining patch in this fixpack also included?

**Comment by vancv** [comment]
Only change in 4.51 is added polish translation. So I assume that patch "310-creature_colouring.tpa.patch" is still needed.

**Comment by lynxlynxlynx** [comment]
Did you try a test install?

**Comment by vancv** [comment]
Yes, both files were patched and mod was installed without problems.

**Comment by lynxlynxlynx** [comment]
Great, good job.

**Pull request merged**
